# Generated by Django 6.1 on 2026-09-26 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0002_asistencia_diaria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asistencia',
            name='gestion',
        ),
    ]
