# Generated by Django 6.1 on 2026-08-13 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0004_estudiante_celular_estudiante_departamento_and_more'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='materia',
            field=models.ForeignKey(blank=True, help_text='Materia que dicta este profesor (aplica solo a usuarios con rol Profesor).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='profesores', to='academico.materia'),
        ),
    ]
