# Generated by Django 6.1 on 2026-08-18 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0006_estudiante_tutor'),
        ('accounts', '0002_usuario_materia'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('PROFESOR', 'Profesor'), ('ESTUDIANTE', 'Estudiante'), ('PADRE', 'Padre/Tutor')], max_length=12),
        ),
        migrations.AddConstraint(
            model_name='usuario',
            constraint=models.UniqueConstraint(condition=models.Q(('rol', 'PADRE')), fields=('ci',), name='unico_ci_por_tutor'),
        ),
    ]
