# Generated by Django 6.1 on 2026-09-07 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_usuario_rol_usuario_unico_ci_por_tutor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('PROFESOR', 'Profesor'), ('ESTUDIANTE', 'Estudiante'), ('PADRE', 'Padre/Tutor'), ('REGENTE', 'Regente')], max_length=12),
        ),
    ]
