# Generated by Django 6.1 on 2026-09-03 02:52

import apps.mensajeria.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_ultimo_mensaje', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('usuario_mayor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversaciones_como_mayor', to=settings.AUTH_USER_MODEL)),
                ('usuario_menor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversaciones_como_menor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conversación',
                'verbose_name_plural': 'Conversaciones',
                'ordering': ['-fecha_ultimo_mensaje', '-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuerpo', models.TextField(blank=True)),
                ('archivo', models.FileField(blank=True, null=True, upload_to=apps.mensajeria.validators.ruta_adjunto_mensaje, validators=[apps.mensajeria.validators.validar_adjunto], verbose_name='Adjunto')),
                ('archivo_nombre', models.CharField(blank=True, max_length=255)),
                ('leido', models.BooleanField(default=False)),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_enviados', to=settings.AUTH_USER_MODEL)),
                ('conversacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='mensajeria.conversacion')),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_recibidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mensaje',
                'verbose_name_plural': 'Mensajes',
                'ordering': ['fecha_envio', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='conversacion',
            constraint=models.UniqueConstraint(fields=('usuario_menor', 'usuario_mayor'), name='unica_conversacion_por_par'),
        ),
        migrations.AddConstraint(
            model_name='conversacion',
            constraint=models.CheckConstraint(condition=models.Q(('usuario_menor__lt', models.F('usuario_mayor'))), name='par_de_conversacion_ordenado'),
        ),
        migrations.AddIndex(
            model_name='mensaje',
            index=models.Index(condition=models.Q(('leido', False)), fields=['destinatario'], name='msg_no_leidos_idx'),
        ),
        migrations.AddIndex(
            model_name='mensaje',
            index=models.Index(fields=['conversacion', 'fecha_envio'], name='msg_conversacion_fecha_idx'),
        ),
    ]
