# Generated by Django 6.1 on 2026-08-18 23:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('NOTICIA', 'Noticia'), ('CITACION', 'Citación'), ('TAREA', 'Tarea')], max_length=12)),
                ('titulo', models.CharField(max_length=200)),
                ('mensaje', models.CharField(blank=True, max_length=300)),
                ('url', models.CharField(max_length=300)),
                ('leida', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(condition=models.Q(('leida', False)), fields=['usuario'], name='notif_no_leidas_idx'), models.Index(fields=['usuario', '-fecha_creacion'], name='notif_usuario_fecha_idx')],
            },
        ),
    ]
