# Generated by Django 6.1 on 2026-09-26 03:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SuscripcionPush',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.URLField(max_length=500, unique=True, verbose_name='Dirección del teléfono')),
                ('p256dh', models.CharField(max_length=120, verbose_name='Llave pública del teléfono')),
                ('auth', models.CharField(max_length=60, verbose_name='Secreto de cifrado')),
                ('dispositivo', models.CharField(blank=True, help_text='Para que el usuario reconozca cuál es.', max_length=120)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('ultimo_envio', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suscripciones_push', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Suscripción push',
                'verbose_name_plural': 'Suscripciones push',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['usuario'], name='push_usuario_idx')],
            },
        ),
    ]
