# Generated by Django 6.1 on 2026-09-26 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0002_suscripcionpush'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='avisada',
            field=models.BooleanField(default=False, verbose_name='Ya salió al celular'),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='nivel',
            field=models.CharField(choices=[('INFO', 'Informativo'), ('ATENCION', 'Atención'), ('URGENTE', 'Urgente')], default='INFO', max_length=8),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('NOTICIA', 'Noticia'), ('CITACION', 'Citación'), ('TAREA', 'Tarea'), ('ASISTENCIA', 'Asistencia'), ('NOTA', 'Calificación')], max_length=12),
        ),
    ]
