# Generated by Django 6.1 on 2026-09-26 03:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0010_gestion_una_sola_gestion_activa'),
        ('notificaciones', '0003_notificacion_avisada_notificacion_nivel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='estudiante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='academico.estudiante'),
        ),
    ]
