# Generated by Django 6.1 on 2026-09-27 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0004_notificacion_estudiante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('NOTICIA', 'Noticia'), ('CITACION', 'Citación'), ('TAREA', 'Tarea'), ('ASISTENCIA', 'Asistencia'), ('NOTA', 'Calificación'), ('MENSAJE', 'Mensaje')], max_length=12),
        ),
    ]
