# Generated by Django 6.1 on 2026-08-13 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='email_tutor',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Correo del padre/tutor'),
        ),
    ]
