# Generated by Django 6.1 on 2026-08-13 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0003_estudiante_email_tutor'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='celular',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='departamento',
            field=models.CharField(blank=True, choices=[('LA_PAZ', 'La Paz'), ('COCHABAMBA', 'Cochabamba'), ('SANTA_CRUZ', 'Santa Cruz'), ('ORURO', 'Oruro'), ('POTOSI', 'Potosí'), ('CHUQUISACA', 'Chuquisaca'), ('TARIJA', 'Tarija'), ('BENI', 'Beni'), ('PANDO', 'Pando')], max_length=15),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='estudiantes/fotos/'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='genero',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='grupo_sanguineo',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='nacionalidad',
            field=models.CharField(blank=True, default='Boliviana', max_length=50),
        ),
    ]
