# Generated by Django 6.1 on 2026-08-13 23:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0004_estudiante_celular_estudiante_departamento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('es_recreo', models.BooleanField(default=False, verbose_name='Es recreo')),
                ('etiqueta', models.CharField(blank=True, help_text='Ej: "Recreo". Opcional.', max_length=50)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periodos', to='academico.curso')),
            ],
            options={
                'verbose_name': 'Período',
                'verbose_name_plural': 'Períodos',
                'ordering': ['curso', 'orden', 'hora_inicio'],
            },
        ),
    ]
