# Generated by Django 6.1 on 2026-08-18 23:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0005_periodo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='tutor',
            field=models.ForeignKey(blank=True, help_text='Se crea y se vincula sola a partir del CI del tutor. No editar a mano.', limit_choices_to={'rol': 'PADRE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hijos', to=settings.AUTH_USER_MODEL, verbose_name='Cuenta de acceso del padre/tutor'),
        ),
    ]
