# Generated by Django 6.1 on 2026-09-07 03:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0006_estudiante_tutor'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaCapacitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(choices=[('LUN', 'Lunes'), ('MAR', 'Martes'), ('MIE', 'Miércoles'), ('JUE', 'Jueves'), ('VIE', 'Viernes')], max_length=3, verbose_name='Día')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dias_capacitacion', to='academico.curso')),
            ],
            options={
                'verbose_name': 'Día de capacitación',
                'verbose_name_plural': 'Días de capacitación',
                'ordering': ['curso', 'dia'],
                'constraints': [models.UniqueConstraint(fields=('curso', 'dia'), name='un_dia_de_capacitacion_por_curso')],
            },
        ),
    ]
