# Generated by Django 6.1 on 2026-09-11 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0008_normalizar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='horario',
            options={'ordering': ['dia', 'periodo__orden'], 'verbose_name': 'Horario', 'verbose_name_plural': 'Horarios'},
        ),
        migrations.AlterModelOptions(
            name='periodo',
            options={'ordering': ['curso', 'orden'], 'verbose_name': 'Período', 'verbose_name_plural': 'Períodos'},
        ),
        migrations.RemoveField(
            model_name='periodo',
            name='hora_fin',
        ),
        migrations.RemoveField(
            model_name='periodo',
            name='hora_inicio',
        ),
        migrations.AlterField(
            model_name='diacapacitacion',
            name='dia',
            field=models.CharField(choices=[('LUN', 'Lunes'), ('MAR', 'Martes'), ('MIE', 'Miércoles'), ('JUE', 'Jueves'), ('VIE', 'Viernes'), ('SAB', 'Sábado')], max_length=3, verbose_name='Día'),
        ),
        migrations.AlterField(
            model_name='horario',
            name='dia',
            field=models.CharField(choices=[('LUN', 'Lunes'), ('MAR', 'Martes'), ('MIE', 'Miércoles'), ('JUE', 'Jueves'), ('VIE', 'Viernes'), ('SAB', 'Sábado')], max_length=3),
        ),
        migrations.AlterField(
            model_name='periodo',
            name='etiqueta',
            field=models.CharField(blank=True, help_text='Cómo se llama en el colegio. Ej: "1°", "Recreo". Opcional.', max_length=50),
        ),
    ]
