# Generated by Django 6.1 on 2026-09-26 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0009_periodos_sin_hora_y_sabado'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='gestion',
            constraint=models.UniqueConstraint(condition=models.Q(('activa', True)), fields=('activa',), name='una_sola_gestion_activa'),
        ),
    ]
