# Generated by Django 6.1 on 2026-08-18 22:27

import apps.tareas.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academico', '0005_periodo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trimestre', models.PositiveSmallIntegerField(choices=[(1, 'Primer trimestre'), (2, 'Segundo trimestre'), (3, 'Tercer trimestre')])),
                ('titulo', models.CharField(max_length=150, verbose_name='Título')),
                ('descripcion', models.TextField(blank=True, verbose_name='Enunciado / descripción')),
                ('fecha_asignacion', models.DateField(default=django.utils.timezone.localdate, verbose_name='Fecha de asignación')),
                ('fecha_entrega', models.DateField(verbose_name='Fecha límite de entrega')),
                ('peso', models.PositiveSmallIntegerField(default=10, help_text='Peso relativo dentro del trimestre (ej: examen 40, práctica 10). No hace falta que los pesos sumen 100.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Peso')),
                ('permite_archivo', models.BooleanField(default=True, verbose_name='El estudiante puede adjuntar un archivo')),
                ('permite_atraso', models.BooleanField(default=True, verbose_name='Permitir entregas después de la fecha límite')),
                ('archivo_adjunto', models.FileField(blank=True, null=True, upload_to=apps.tareas.validators.ruta_enunciado, validators=[apps.tareas.validators.validar_archivo], verbose_name='Archivo del enunciado')),
                ('archivo_nombre', models.CharField(blank=True, max_length=255)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('asignacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='academico.asignaciondocente', verbose_name='asignación')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tarea',
                'verbose_name_plural': 'Tareas',
                'ordering': ['trimestre', 'fecha_entrega', 'id'],
                'unique_together': {('asignacion', 'trimestre', 'titulo')},
            },
        ),
        migrations.CreateModel(
            name='EntregaTarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ENTREGADA', 'Entregada'), ('ATRASADA', 'Entregada con retraso'), ('NO_ENTREGADA', 'No entregada')], default='PENDIENTE', max_length=15)),
                ('archivo', models.FileField(blank=True, null=True, upload_to=apps.tareas.validators.ruta_entrega, validators=[apps.tareas.validators.validar_archivo])),
                ('archivo_nombre', models.CharField(blank=True, max_length=255)),
                ('comentario_estudiante', models.TextField(blank=True, verbose_name='Comentario del estudiante')),
                ('fecha_entrega_real', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de entrega')),
                ('nota', models.DecimalField(blank=True, decimal_places=2, help_text='Vacío = sin calificar todavía.', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('observacion', models.TextField(blank=True, verbose_name='Observación del profesor')),
                ('fecha_calificacion', models.DateTimeField(blank=True, null=True)),
                ('calificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entregas_calificadas', to=settings.AUTH_USER_MODEL)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas_tareas', to='academico.estudiante')),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to='tareas.tarea')),
            ],
            options={
                'verbose_name': 'Entrega de tarea',
                'verbose_name_plural': 'Entregas de tareas',
                'ordering': ['estudiante__usuario__last_name', 'estudiante__usuario__first_name'],
                'unique_together': {('tarea', 'estudiante')},
            },
        ),
    ]
