# Generated by Django 6.1 on 2026-09-23 00:22

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calificaciones', '0002_nota_autoevaluacion_nota_autoevaluacion_por_and_more'),
        ('tareas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarea',
            name='peso',
        ),
        migrations.AddField(
            model_name='tarea',
            name='actividad',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tarea', to='calificaciones.actividad'),
        ),
        migrations.AlterField(
            model_name='entregatarea',
            name='nota',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Vacío = sin calificar todavía. Se califica sobre 40.', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(Decimal('40'))]),
        ),
    ]
