# Generated by Django 6.1 on 2026-08-18 23:43

import apps.noticias.validators
import apps.tareas.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academico', '0006_estudiante_tutor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('cuerpo', models.TextField(verbose_name='Contenido')),
                ('tipo', models.CharField(choices=[('NOTICIA', 'Noticia'), ('ACTIVIDAD', 'Actividad'), ('COMUNICADO', 'Comunicado')], default='NOTICIA', max_length=12)),
                ('fecha_evento', models.DateField(blank=True, null=True, verbose_name='Fecha de la actividad')),
                ('imagen', models.ImageField(blank=True, upload_to=apps.noticias.validators.ruta_imagen_noticia, validators=[apps.noticias.validators.validar_imagen])),
                ('archivo', models.FileField(blank=True, upload_to=apps.noticias.validators.ruta_adjunto_noticia, validators=[apps.tareas.validators.validar_archivo], verbose_name='Archivo adjunto')),
                ('archivo_nombre', models.CharField(blank=True, max_length=255)),
                ('publicada', models.BooleanField(default=True, verbose_name='Visible para los destinatarios')),
                ('fijada', models.BooleanField(default=False, verbose_name='Fijar arriba')),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('curso', models.ForeignKey(blank=True, help_text='Dejar vacío para publicar a todo el colegio.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='noticias', to='academico.curso')),
                ('publicado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='noticias_publicadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Noticia',
                'verbose_name_plural': 'Noticias',
                'ordering': ['-fijada', '-fecha_publicacion'],
                'indexes': [models.Index(fields=['publicada', 'curso'], name='noticia_pub_curso_idx')],
            },
        ),
    ]
