# Generated by Django 6.1 on 2026-08-13 03:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academico', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Citacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField(verbose_name='Motivo de la citación')),
                ('fecha', models.DateField(verbose_name='Fecha de la citación')),
                ('hora', models.TimeField(blank=True, null=True, verbose_name='Hora')),
                ('lugar', models.CharField(blank=True, default='Dirección del colegio', max_length=150)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ATENDIDA', 'Atendida'), ('NO_ASISTIO', 'No asistió')], default='PENDIENTE', max_length=12)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citaciones', to='academico.estudiante')),
                ('generado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citaciones_generadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Citación',
                'verbose_name_plural': 'Citaciones',
                'ordering': ['-fecha'],
            },
        ),
    ]
