# Generated by Django 6.1 on 2026-08-14 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunicaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='citacion',
            name='es_automatica',
            field=models.BooleanField(default=False, verbose_name='Generada automáticamente'),
        ),
    ]
