# Generated by Django 6.1 on 2026-09-26 03:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0010_gestion_una_sola_gestion_activa'),
        ('comunicaciones', '0002_citacion_es_automatica'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertaEmitida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=80)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas_emitidas', to='academico.estudiante')),
            ],
            options={
                'verbose_name': 'Alerta emitida',
                'verbose_name_plural': 'Alertas emitidas',
                'ordering': ['-fecha_creacion'],
                'constraints': [models.UniqueConstraint(fields=('estudiante', 'clave'), name='una_alerta_por_hecho')],
            },
        ),
    ]
