# Generated by Django 6.1 on 2026-09-22 23:07

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0009_periodos_sin_hora_y_sabado'),
        ('calificaciones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='nota',
            name='autoevaluacion',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='De 0 a 5. La pone el estudiante o su docente.', max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(Decimal('5'))], verbose_name='Autoevaluación'),
        ),
        migrations.AddField(
            model_name='nota',
            name='autoevaluacion_por',
            field=models.ForeignKey(blank=True, help_text='Quién la puso: sirve para que el docente sepa si el estudiante ya se evaluó.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='autoevaluaciones_puestas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='nota',
            name='extracurricular',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='De 0 a 5 puntos. Se suman, pero el trimestre no pasa de 100.', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(Decimal('5'))], verbose_name='Actividad extracurricular'),
        ),
        migrations.AddField(
            model_name='nota',
            name='hacer',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Hacer'),
        ),
        migrations.AddField(
            model_name='nota',
            name='saber',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Saber'),
        ),
        migrations.AddField(
            model_name='nota',
            name='ser',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Ser'),
        ),
        migrations.AlterField(
            model_name='nota',
            name='nota',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Nota del trimestre'),
        ),
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trimestre', models.PositiveSmallIntegerField(choices=[(1, 'Primer trimestre'), (2, 'Segundo trimestre'), (3, 'Tercer trimestre')])),
                ('dimension', models.CharField(choices=[('SER', 'Ser'), ('SABER', 'Saber'), ('HACER', 'Hacer')], max_length=5)),
                ('nombre', models.CharField(max_length=60)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('asignacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='academico.asignaciondocente')),
                ('creada_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actividades_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Actividad',
                'verbose_name_plural': 'Actividades',
                'ordering': ['asignacion', 'trimestre', 'dimension', 'orden', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='Puntaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('fecha_registro', models.DateTimeField(auto_now=True)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puntajes', to='calificaciones.actividad')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puntajes', to='academico.estudiante')),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='puntajes_registrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Puntaje',
                'verbose_name_plural': 'Puntajes',
                'ordering': ['actividad', 'estudiante'],
            },
        ),
        migrations.AddConstraint(
            model_name='actividad',
            constraint=models.UniqueConstraint(fields=('asignacion', 'trimestre', 'dimension', 'orden'), name='un_orden_por_dimension'),
        ),
        migrations.AddConstraint(
            model_name='puntaje',
            constraint=models.UniqueConstraint(fields=('actividad', 'estudiante'), name='un_puntaje_por_actividad'),
        ),
    ]
