# Generated by Django 6.1 on 2026-09-26 02:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0010_gestion_una_sola_gestion_activa'),
        ('calificaciones', '0002_nota_autoevaluacion_nota_autoevaluacion_por_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='nombre',
            field=models.CharField(blank=True, help_text='Vacío cuando la actividad es una tarea: el nombre lo pone la tarea.', max_length=60),
        ),
        migrations.AddConstraint(
            model_name='nota',
            constraint=models.CheckConstraint(condition=models.Q(('nota__gte', 0), ('nota__lte', 100)), name='nota_en_rango'),
        ),
        migrations.AddConstraint(
            model_name='nota',
            constraint=models.CheckConstraint(condition=models.Q(('autoevaluacion__isnull', True), models.Q(('autoevaluacion__gte', 0), ('autoevaluacion__lte', 5)), _connector='OR'), name='autoevaluacion_en_rango'),
        ),
        migrations.AddConstraint(
            model_name='nota',
            constraint=models.CheckConstraint(condition=models.Q(('extracurricular__gte', 0), ('extracurricular__lte', 5)), name='extracurricular_en_rango'),
        ),
        migrations.AddConstraint(
            model_name='puntaje',
            constraint=models.CheckConstraint(condition=models.Q(('valor__gte', 0), ('valor__lte', 45)), name='puntaje_en_rango'),
        ),
    ]
